FROM node:18-alpine
WORKDIR /app
# index.html dosyasını da kopyalayın
COPY package.json tsconfig.json vite.config.ts index.html ./
COPY src ./src
RUN npm install
CMD ["npm", "run", "dev", "--", "--host"]
